"""Persistent JSON store for single-use tenant JOIN keys.

A JOIN key is generated by the Provider Admin when preparing a new tenant slot
in the CDM dashboard.  It is handed to the tenant operator out-of-band (e.g.
shown in the UI, copied to .env).  When the Tenant-Stack boots it presents the
key in a single HTTP call to the Provider API and receives the full provisioning
bundle immediately.  The key is then marked ``used`` and cannot be reused.

File structure (``settings.join_keys_db_path``)::

    {
        "A3F9-KJ2M-XP7N-QR5C": {
            "key":          "A3F9-KJ2M-XP7N-QR5C",
            "tenant_id":    "acme-corp",
            "display_name": "ACME Corp",
            "status":       "open | used | revoked",
            "created_at":   "ISO8601",
            "expires_at":   "ISO8601",
            "used_at":      null
        }
    }
"""

from __future__ import annotations

import asyncio
import json
import secrets
import string
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, cast

from app.config import Settings

_key_lock: asyncio.Lock = asyncio.Lock()

# Key TTL: JOIN keys expire 7 days after generation.
JOIN_KEY_TTL_HOURS: int = 7 * 24

# Key format: 4 groups of 4 uppercase alphanumeric chars separated by hyphens.
_ALPHABET = string.ascii_uppercase + string.digits
_GROUP_LEN = 4
_NUM_GROUPS = 4


def generate_join_key() -> str:
    """Generate a cryptographically secure JOIN key in XXXX-YYYY-ZZZZ-WWWW format."""
    groups = [
        "".join(secrets.choice(_ALPHABET) for _ in range(_GROUP_LEN)) for _ in range(_NUM_GROUPS)
    ]
    return "-".join(groups)


def _store_path(settings: Settings) -> Path:
    return Path(settings.join_keys_db_path)


async def load_keys(settings: Settings) -> dict[str, Any]:
    """Return the full key dict from disk.  Returns {} if the file is missing."""
    path = _store_path(settings)
    if not path.exists():
        return {}
    async with _key_lock:
        return cast(dict[str, Any], json.loads(path.read_text()))


async def save_keys(data: dict[str, Any], settings: Settings) -> None:
    """Persist the key dict to disk (atomic rename)."""
    path = _store_path(settings)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".keys.tmp")
    async with _key_lock:
        tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False))
        tmp.replace(path)


async def create_key(tenant_id: str, display_name: str, settings: Settings) -> str:
    """Create a new open JOIN key for *tenant_id* and persist it.

    Returns the generated key string.
    """
    key = generate_join_key()
    now = datetime.now(UTC)
    expires_at = now + timedelta(hours=JOIN_KEY_TTL_HOURS)

    keys = await load_keys(settings)
    keys[key] = {
        "key": key,
        "tenant_id": tenant_id,
        "display_name": display_name,
        "status": "open",
        "created_at": now.isoformat(),
        "expires_at": expires_at.isoformat(),
        "used_at": None,
    }
    await save_keys(keys, settings)
    return key


async def validate_and_consume(key: str, settings: Settings) -> dict[str, Any]:
    """Validate the key and mark it as *used*.

    Returns the key entry dict if valid.

    Raises:
        KeyError:   key does not exist.
        ValueError: key is already used, revoked, or expired.
    """
    keys = await load_keys(settings)
    entry = keys.get(key)
    if entry is None:
        raise KeyError(f"JOIN key not found: {key!r}")

    if entry["status"] != "open":
        raise ValueError(f"JOIN key is {entry['status']!r} – each key may only be used once.")

    expires_at = datetime.fromisoformat(entry["expires_at"])
    if datetime.now(UTC) > expires_at:
        # Expire it in the store too
        entry["status"] = "expired"
        keys[key] = entry
        await save_keys(keys, settings)
        raise ValueError("JOIN key has expired.")

    entry["status"] = "used"
    entry["used_at"] = datetime.now(UTC).isoformat()
    keys[key] = entry
    await save_keys(keys, settings)
    return cast(dict[str, Any], entry)
