version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install -r docs/requirements.txt
    - zensical build
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r site/* $READTHEDOCS_OUTPUT/html/
