name: 🚀 Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement!
        Please fill in as much detail as you can so we can evaluate and prioritise the request.

  - type: dropdown
    id: component
    attributes:
      label: Target Component
      description: Which area would this feature improve?
      options:
        - cloud-infrastructure / docker-compose
        - step-ca (PKI)
        - keycloak (IAM)
        - thingsboard (UI / MQTT / Rule Chain)
        - hawkbit (OTA backend)
        - influxdb / grafana (monitoring)
        - wireguard (VPN)
        - glue-services / iot-bridge-api
        - glue-services / terminal-proxy
        - device-stack
        - kubernetes / helm charts
        - documentation
        - CI / GitHub Actions
        - new component (describe below)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem are you trying to solve? Why is this important?
      placeholder: "Currently there is no way to ... which means I have to ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like. Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      options:
        - Critical — blocks my use-case completely
        - High — significant workaround required
        - Medium — nice to have, minor workaround exists
        - Low — cosmetic / optional improvement
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues/discussions and this has not been requested before.
          required: true
        - label: I am willing to contribute a PR for this feature if it is accepted.
          required: false
