#!/bin/sh
# init-sub-ca.sh – Tenant Stack step-ca Sub-CA initialisation
#
# This script performs TWO tasks that must run once after the first start:
#
# Task 1 – Key-based JOIN handshake with the Provider IoT Bridge API
#   Generates a Sub-CA CSR, sends a single authenticated POST request to the
#   Provider API (X-Join-Key header), and immediately receives the full
#   provisioning bundle (signed Sub-CA cert, Root CA cert, RabbitMQ config,
#   MQTT bridge cert, Keycloak federation credentials).
#   The JOIN key is single-use and is invalidated by the Provider after this call.
#
#   Required env vars:
#     PROVIDER_URL        – e.g. https://provider.iot.example.com/api
#     JOIN_KEY            – XXXX-YYYY-ZZZZ-WWWW (generated by CDM Dashboard)
#     TENANT_ID           – unique slug for this tenant
#     TENANT_DISPLAY_NAME – human-readable name
#
#   Optional:
#     TENANT_KEYCLOAK_URL – external Keycloak URL, forwarded to the Provider
#                           for Keycloak federation client creation
#
#   If PROVIDER_URL or JOIN_KEY is not set, the Sub-CA runs in standalone mode.
#
# Task 2 – Add IoT Bridge API JWK provisioner
#   Adds a dedicated JWK provisioner for the iot-bridge-api.
#
# Usage (from the host):
#   docker compose exec ${TENANT_ID:-tenant}-step-ca /usr/local/bin/init-sub-ca.sh

set -eu

CA_CONFIG="/home/step/config/ca.json"
CA_URL="https://localhost:9000"
ROOT_CERT="/home/step/certs/root_ca.crt"
INTERMEDIATE_CERT="/home/step/certs/intermediate_ca.crt"
CA_KEY="/home/step/secrets/intermediate_ca_key"

PROVISIONER_NAME="${STEP_CA_PROVISIONER_NAME:-iot-bridge}"
PROVISIONER_PASSWORD="${STEP_CA_PROVISIONER_PASSWORD:-changeme}"
DEVICE_TEMPLATE="/home/step/templates/device-leaf.tpl"
ADMIN_PROVISIONER="${DOCKER_STEPCA_INIT_PROVISIONER_NAME:-tenant-admin@cdm.local}"
TENANT_ID="${TENANT_ID:-tenant}"
TENANT_DISPLAY_NAME="${TENANT_DISPLAY_NAME:-Tenant $TENANT_ID}"
TENANT_KEYCLOAK_URL="${TENANT_KEYCLOAK_URL:-}"

PROVIDER_URL="${PROVIDER_URL:-}"
JOIN_KEY="${JOIN_KEY:-}"

# Tenant Keycloak admin (used to register Provider KC as IdP in the Tenant realm)
KC_INTERNAL_URL="${KC_INTERNAL_URL:-http://keycloak:8080/auth}"
KC_ADMIN_USER="${KC_ADMIN_USER:-admin}"
KC_ADMIN_PASSWORD="${KC_ADMIN_PASSWORD:-changeme}"

if [ ! -f "$CA_CONFIG" ]; then
  echo "ERROR: $CA_CONFIG not found – run container first to trigger DOCKER_STEPCA_INIT."
  exit 1
fi

echo ">>> Bootstrapping trust against local CA..."
step ca bootstrap \
  --ca-url "$CA_URL" \
  --fingerprint "$(step certificate fingerprint "$ROOT_CERT")" \
  --force

# ── Task 1: Key-based JOIN handshake ────────────────────────────────────────
if [ -n "$PROVIDER_URL" ] && [ -n "$JOIN_KEY" ]; then
  PROVIDER_API="${PROVIDER_URL%/}"
  CSR_FILE="/tmp/tenant-sub-ca.csr"
  KEY_FILE="/tmp/tenant-sub-ca.key"
  MQTT_CSR_FILE="/tmp/mqtt-bridge.csr"
  MQTT_KEY_FILE="/tmp/mqtt-bridge.key"
  MQTT_BRIDGE_DIR="/home/step/mqtt-bridge"

  echo ""
  echo ">>> Generating Sub-CA key pair and CSR for tenant: $TENANT_ID ..."
  step certificate create \
    "$TENANT_DISPLAY_NAME Issuing CA" \
    "$CSR_FILE" \
    "$KEY_FILE" \
    --kty EC \
    --curve P-256 \
    --csr \
    --no-password \
    --insecure

  echo ">>> Generating MQTT bridge client key pair and CSR ..."
  mkdir -p "$MQTT_BRIDGE_DIR"
  step certificate create \
    "${TENANT_ID}-mqtt-bridge" \
    "$MQTT_CSR_FILE" \
    "$MQTT_KEY_FILE" \
    --kty EC \
    --curve P-256 \
    --csr \
    --no-password \
    --insecure

  # Read WireGuard public key if available, else send placeholder
  WG_PUBKEY=""
  if [ -f /etc/wireguard/pub_key ]; then
    WG_PUBKEY="$(cat /etc/wireguard/pub_key)"
  elif command -v wg >/dev/null 2>&1; then
    WG_PUBKEY="$(wg pubkey < /etc/wireguard/priv_key 2>/dev/null || true)"
  fi
  WG_PUBKEY="${WG_PUBKEY:-not-available}"

  # Embed PEM blocks as single-line JSON strings
  _json_pem() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g' | awk '{printf "%s\\n", $0}' | sed '$ s/\\n$//'; }

  CSR_PEM="$(cat "$CSR_FILE")"
  MQTT_CSR_PEM="$(cat "$MQTT_CSR_FILE")"

  PAYLOAD=$(printf '{"sub_ca_csr":"%s","wg_pubkey":"%s","keycloak_url":"%s","mqtt_bridge_csr":"%s"}' \
    "$(_json_pem "$CSR_PEM")" \
    "$WG_PUBKEY" \
    "$TENANT_KEYCLOAK_URL" \
    "$(_json_pem "$MQTT_CSR_PEM")")

  echo ">>> Sending JOIN handshake to $PROVIDER_API/portal/admin/join ..."
  RESPONSE_FILE="/tmp/join-response.json"
  HTTP_CODE=$(curl -sf -o "$RESPONSE_FILE" -w "%{http_code}" \
    -X POST \
    -H "Content-Type: application/json" \
    -H "X-Join-Key: ${JOIN_KEY}" \
    -d "$PAYLOAD" \
    "$PROVIDER_API/portal/admin/join" \
    2>/dev/null) || HTTP_CODE="000"

  if [ "$HTTP_CODE" != "200" ]; then
    echo "ERROR: JOIN handshake failed with HTTP $HTTP_CODE."
    echo "       Check PROVIDER_URL and JOIN_KEY.  JOIN keys are single-use and expire after 7 days."
    echo "       Generate a new key in the CDM Dashboard (Provider → Tenants → Prepare)."
    echo "       Continuing in standalone mode."
  else
    echo ">>> JOIN handshake succeeded (HTTP 200)! Installing provisioning bundle..."
    BUNDLE="$RESPONSE_FILE"

    _jq() { python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$1',''))" < "$BUNDLE" 2>/dev/null || true; }

    SIGNED_CERT="$(_jq signed_cert)"
    ROOT_CA_DATA="$(_jq root_ca_cert)"

    if [ -n "$SIGNED_CERT" ]; then
      printf '%s\n' "$SIGNED_CERT" > "$INTERMEDIATE_CERT"
      echo "    Sub-CA certificate installed."
    fi
    if [ -n "$ROOT_CA_DATA" ]; then
      printf '%s\n' "$ROOT_CA_DATA" > "$ROOT_CERT"
      echo "    Provider Root CA certificate installed."
    fi

    # Install Sub-CA private key
    if [ -f "$KEY_FILE" ]; then
      cp "$KEY_FILE" "$CA_KEY"
      chmod 600 "$CA_KEY"
      echo "    Sub-CA private key installed."
    fi

    # Install MQTT bridge certificate and key
    MQTT_CERT="$(_jq mqtt_bridge_cert)"
    if [ -n "$MQTT_CERT" ]; then
      mkdir -p "$MQTT_BRIDGE_DIR"
      printf '%s\n' "$MQTT_CERT" > "$MQTT_BRIDGE_DIR/client.crt"
      cp "$MQTT_KEY_FILE" "$MQTT_BRIDGE_DIR/client.key"
      chmod 600 "$MQTT_BRIDGE_DIR/client.key"
      [ -n "$ROOT_CA_DATA" ] && printf '%s\n' "$ROOT_CA_DATA" > "$MQTT_BRIDGE_DIR/ca.crt"
      echo "    MQTT bridge certificates installed in $MQTT_BRIDGE_DIR"
    fi

    # Write RabbitMQ connection config
    RMQ_URL="$(_jq rabbitmq_url)"
    RMQ_VHOST="$(_jq rabbitmq_vhost)"
    RMQ_USER="$(_jq rabbitmq_user)"
    if [ -n "$RMQ_URL" ]; then
      mkdir -p /home/step/join-bundle
      MQTTS_HOST=$(printf '%s' "$RMQ_URL" | sed 's|http://||; s|https://||; s|:.*||')
      printf 'RABBITMQ_MQTTS_URL=mqtts://%s:8883\nRABBITMQ_VHOST=%s\nRABBITMQ_USER=%s\nRABBITMQ_TLS_CERT=%s/client.crt\nRABBITMQ_TLS_KEY=%s/client.key\nRABBITMQ_TLS_CA=%s/ca.crt\n' \
        "$MQTTS_HOST" "$RMQ_VHOST" "$RMQ_USER" \
        "$MQTT_BRIDGE_DIR" "$MQTT_BRIDGE_DIR" "$MQTT_BRIDGE_DIR" \
        > /home/step/join-bundle/rabbitmq.env
      echo "    MQTT connection config written to /home/step/join-bundle/rabbitmq.env"
    fi

    # Extract Keycloak federation credentials
    CDM_IDP_CLIENT_ID="$(_jq cdm_idp_client_id)"
    CDM_IDP_SECRET="$(_jq cdm_idp_client_secret)"
    CDM_DISC_URL="$(_jq cdm_discovery_url)"

    # Always write federation credentials for reference / manual setup
    mkdir -p /home/step/join-bundle
    printf 'CDM_IDP_CLIENT_ID=%s\nCDM_IDP_CLIENT_SECRET=%s\nCDM_DISCOVERY_URL=%s\nKC_IDP_ALIAS=cdm-provider\n' \
      "$CDM_IDP_CLIENT_ID" "$CDM_IDP_SECRET" "$CDM_DISC_URL" \
      > /home/step/join-bundle/keycloak-federation.env
    echo "    Keycloak federation credentials written to /home/step/join-bundle/keycloak-federation.env"

    # Register Provider Keycloak as Identity Provider in the Tenant Keycloak realm
    if [ -n "$CDM_IDP_CLIENT_ID" ] && [ -n "$KC_INTERNAL_URL" ]; then
      echo ">>> Registering Provider as IdP in Tenant KC realm '${TENANT_ID}' ..."
      KC_BASE="${KC_INTERNAL_URL%/}"

      python3 -c "
import json, sys
print(json.dumps({
  'alias': 'cdm-provider',
  'displayName': 'CDM Platform (Provider)',
  'providerId': 'oidc',
  'enabled': True,
  'trustEmail': True,
  'storeToken': False,
  'addReadTokenRoleOnCreate': False,
  'config': {
    'clientId': sys.argv[1],
    'clientSecret': sys.argv[2],
    'metadataDescriptorUrl': sys.argv[3],
    'useJwksUrl': 'true',
    'syncMode': 'FORCE',
    'defaultScope': 'openid profile email roles',
  }
}))
" "$CDM_IDP_CLIENT_ID" "$CDM_IDP_SECRET" "$CDM_DISC_URL" > /tmp/kc-idp-payload.json 2>/dev/null || true

      KC_TOKEN=$(curl -sf -X POST \
        "${KC_BASE}/realms/master/protocol/openid-connect/token" \
        -d 'grant_type=password&client_id=admin-cli' \
        --data-urlencode "username=${KC_ADMIN_USER}" \
        --data-urlencode "password=${KC_ADMIN_PASSWORD}" \
        | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null || true)

      if [ -n "$KC_TOKEN" ] && [ -s /tmp/kc-idp-payload.json ]; then
        IDP_HTTP=$(curl -sf -o /dev/null -w "%{http_code}" -X POST \
          "${KC_BASE}/admin/realms/${TENANT_ID}/identity-provider/instances" \
          -H "Authorization: Bearer ${KC_TOKEN}" \
          -H "Content-Type: application/json" \
          -d @/tmp/kc-idp-payload.json 2>/dev/null || echo "000")
        if [ "$IDP_HTTP" = "201" ] || [ "$IDP_HTTP" = "409" ]; then
          echo "    IdP 'cdm-provider' registered in Tenant KC (HTTP ${IDP_HTTP})."
          echo "    CDM Admins can now log into Tenant services via Provider Keycloak SSO."
        else
          echo "    WARNING: IdP registration returned HTTP ${IDP_HTTP}."
          echo "    Configure manually: Tenant KC Admin → Realm '${TENANT_ID}' → Identity Providers."
          echo "    Use credentials from /home/step/join-bundle/keycloak-federation.env"
        fi
        rm -f /tmp/kc-idp-payload.json
      else
        echo "    WARNING: Could not reach Tenant KC. Skipping auto-registration."
        echo "    Configure manually using /home/step/join-bundle/keycloak-federation.env"
      fi
    fi

    echo ""
    echo ">>> JOIN handshake complete."
    echo "    Chain: Provider Root CA → Tenant ($TENANT_ID) Sub-CA → Device Leaf Certs"
    echo "    The JOIN key has been invalidated by the Provider."
    echo "    You may remove JOIN_KEY from the .env file."
    rm -f "$RESPONSE_FILE"
  fi
else
  echo ""
  echo "INFO: PROVIDER_URL or JOIN_KEY not set – running in standalone mode."
  echo "      To join the Provider:"
  echo "        1. Open CDM Dashboard → Tenants → Prepare Tenant"
  echo "        2. Set PROVIDER_URL and JOIN_KEY in tenant-stack/.env"
  echo "        3. Re-run:  docker compose exec ${TENANT_ID}-step-ca /usr/local/bin/init-sub-ca.sh"
fi

# ── Task 2: Add IoT Bridge API JWK provisioner ──────────────────────────────
echo ""
echo ">>> Adding JWK provisioner: $PROVISIONER_NAME ..."
echo "$PROVISIONER_PASSWORD" | step ca provisioner add "$PROVISIONER_NAME" \
  --type JWK \
  --create \
  --password-file /dev/stdin \
  --admin-provisioner "$ADMIN_PROVISIONER" \
  --admin-password-file /run/secrets/step-ca-password

echo ">>> Attaching device-leaf template to provisioner $PROVISIONER_NAME ..."
step ca provisioner update "$PROVISIONER_NAME" \
  --x509-template "$DEVICE_TEMPLATE" \
  --admin-provisioner "$ADMIN_PROVISIONER" \
  --admin-password-file /run/secrets/step-ca-password

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "=== Tenant Sub-CA setup complete ==="
echo ""
echo "Sub-CA fingerprint (needed for STEP_CA_FINGERPRINT in .env):"
step certificate fingerprint "$ROOT_CERT"
echo ""
echo "Add the following to tenant-stack/.env:"
echo "  STEP_CA_FINGERPRINT=$(step certificate fingerprint "$ROOT_CERT")"
echo "  STEP_CA_PROVISIONER_NAME=$PROVISIONER_NAME"
echo "  STEP_CA_PROVISIONER_PASSWORD=$PROVISIONER_PASSWORD"
echo ""
