apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb-provider
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: cdm
    user: grafana
    secureJsonData:
      password: ${TSDB_GRAFANA_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    isDefault: true
    editable: false

