apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb-provider
    type: grafana-postgresql-datasource
    access: proxy
    url: timescaledb:5432
    user: grafana
    secureJsonData:
      password: ${TSDB_GRAFANA_PASSWORD}
    jsonData:
      database: cdm
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
      schema: public
    isDefault: true
    editable: false
